<?php
$sql  = "SELECT `child_list`.`parent_file_id`,`child_list`.`new_filename`,`child_list`.`token`, `requests`.`count` as visitors FROM child_list, requests WHERE `child_list`.`token` = `requests`.`child_token` ORDER BY visitors DESC";
$k = $db->query($sql);
$data = array();
if ($k->num_rows > 0) {
    while ($u = $k->fetch_assoc()) $data[] = $u;
}
?>
<div class="container-fluid">

    <h1 class="h3 mb-2 text-gray-800">Most viewed list</h1>
    <p class="mb-4">Here is the list of most viewed files</p>
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Most viewed
            </h6>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>Parent ID</th>
                            <th>Child Name</th>
                            <th>Token</th>
                            <th>Visitors</th>
                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            <th>Parent ID</th>
                            <th>Child Name</th>
                            <th>Token</th>
                            <th>Visitors</th>
                        </tr>
                    </tfoot>
                    <tbody>
                        <?php
                        foreach ($data as $item) {
                        ?>
                            <tr>
                                <td><?php echo $item['parent_file_id']; ?></td>
                                <td><?php echo $item['new_filename']; ?></td>
                                <td><?php echo $item['token']; ?></td>
                                <td><?php echo $item['visitors']; ?></td>
                            </tr>
                        <?php
                        }
                        ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>

</div>