<?php
$sql  = "SELECT * FROM fileslist WHERE 1 ORDER BY id DESC";
$k = $db->query($sql);
$data = array();
if ($k->num_rows > 0) {
    while ($u = $k->fetch_assoc()) $data[] = $u;
}
?>
<div class="container-fluid">

    <h1 class="h3 mb-2 text-gray-800">Files</h1>
    <p class="mb-4">list of parent files change, insert, delete and update! </p>
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Parent Files List
                <button class="ml-5 btn btn-primary" data-toggle="modal" data-target="#exampleModal" onclick="addNewFileInList()">Add new file</button>
            </h6>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>File ID</th>
                            <th>Filename</th>
                            <th>Base URL</th>
                            <th>Cache</th>
                            <th>Output</th>
                            <th>Processing</th>
                            <th>Complete</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            <th>File ID</th>
                            <th>Filename</th>
                            <th>Base URL</th>
                            <th>Cache</th>
                            <th>Output</th>
                            <th>Processing</th>
                            <th>Complete</th>
                            <th>Action</th>
                        </tr>
                    </tfoot>
                    <tbody>
                        <?php
                        foreach ($data as $item) {
                        ?>
                            <tr>
                                <td><?php echo $item['id']; ?></td>
                                <td><?php echo $item['filename']; ?></td>
                                <td><?php echo $item['base_url']; ?></td>
                                <td><?php echo $item['cache']; ?></td>
                                <td><?php echo $item['finalLink']; ?></td>
                                <td><?php echo $item['referToBot'] ? 'Yes' : 'No'; ?></td>
                                <td><?php echo $item['complete'] ? 'Yes' : 'No'; ?></td>
                                <td style="min-width: 248px">
                                    <button class="btn btn-danger" onclick="handleDeleteFile(<?php echo $item['id']; ?>)">Delete</button>
                                    <button class="btn btn-primary" data-toggle="modal" data-target="#exampleModal" onclick="handleEditFile({id: <?php echo $item['id'] ?>, filename: '<?php echo $item['filename'] ?>', base_url:'<?php echo $item['base_url'] ?>', cache:'<?php echo $item['cache'] ?>', finalLink: '<?php echo $item['finalLink']; ?>'})">Edit</button>
                                    <button class="btn btn-primary" data-toggle="modal" data-target="#exampleModal" onclick="addChildModal(<?php echo $item['id'] ?>)">Add child</button>
                                </td>
                            </tr>
                        <?php
                        }
                        ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>

</div>